spring:
  cloud:
    gateway:
      routes:
        - id: auth_route
          uri: lb://hotel-auth-server
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth(?<segment>/?.*), $\{segment}